name: Request a feature
description: Request a brand new feature.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out an issue. This template is intended for any feature requests.
        For feedback or help running Don't Get Stabbed, please join our [Discord](https://discord.gg/Rk9wnKswpz).
#  - type: input #TODO put back once build system works on github
#    attributes:
#      label: What version did the issue occur in?
#      description: You can find the version by opening the changelog in-game and looking at the bottom right corner of the changelog window.
#      placeholder: wizards/aa1337b
#    validations:
#      required: false
  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of what the new feature is and how it should work.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other additional context about the feature here.
    validations:
      required: false

