blank_issues_enabled: true
contact_links:
  - name: Request a Feature
    url: https://discord.gg/Rk9wnKswpz
    about: You can also submit feature requests on our Discord server (https://discord.gg/Rk9wnKswpz).
