#Gang Member
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleGangMember
  name: Gang Member Role
  components:
  - type: MindRole
    antagPrototype: GangMember          # must match your antag prototype id
    roleType: GangMember
    subtype: role-subtype-gang-member  # any unique string is fine
  - type: GangMemberRole               # your C# component (GangMemberRoleComponent)

#Shot Caller
- type: entity
  parent: BaseMindRole
  id: MindRoleShotCaller
  name: Shot Caller
  components:
  - type: ShotCallerRole
#  - type: MindRole #TODO see if I need this
#    sortWeight: -10
